### ISSUE TITLE
As a user i want to see a main menu when opening the game, so I can select what to do next

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#1]
**Acceptance Criteria:**
- [x] Criteria 1: Game window opens.
- [x] Criteria 2: Main Menu has the following buttons: 
    - [x] Start game
    - [x] Options
    - [x] Exit
- [x] Criteria 3: Main menu has background that fits with battleship.

**Tasks:**
- [x] Make program open window of size 1280x720
- [x] Add background
- [x] Add Start game button
- [x] Add options button
- [x] Add exit button

**Definition of Done:**
- [x] All acceptance criteria are met.
- [x] All tasks are done
