### ISSUE TITLE
[USER STORY] As a user i want a functional save changes button, so I can save changes i made to my options

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#10]
**Acceptance Criteria:**
- [ ] Criteria 1: Describe the first acceptance criterion here.
- [ ] Criteria 2: Describe the second acceptance criterion here.
- [ ] Criteria 3: Describe additional criteria as needed.

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
