### ISSUE TITLE
As a user I want to see a window with game modes when I click start game, so I can choose which mode I play

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#11]
**Acceptance Criteria:**
- [x] Criteria 1: New pop up window opens.
- [x] Criteria 2: Options are Single player easy, single player hard, local 2 player
- [x] Criteria 3: Player can click back or close the pop up with X

**Tasks:**
- [ ]

**Definition of Done:**
- [x] All acceptance criteria are met.
- [x] All tasks are done
