### ISSUE TITLE
As a user i want to see the gameboard when I choose single player easy, so i can see the gameboard

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#12]
**Acceptance Criteria:**
- [ ] Criteria 1: Describe the first acceptance criterion here.
- [ ] Criteria 2: Describe the second acceptance criterion here.
- [ ] Criteria 3: Describe additional criteria as needed.

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
