### ISSUE TITLE
As a user i want to hear background music

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#13]
**Acceptance Criteria:**
- [ ] Criteria 1: Random song from about 10 songs plays in background.

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
