### ISSUE TITLE
As a user I want the game to close when I press exit, so i can do usefull things

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#2]
**Acceptance Criteria:**
- [ ] Criteria 1: When exit button is pressed the game closes.

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
