### ISSUE TITLE
[USER STORY] As a user when i press the options button, i want the game to open the options window so i can see several options

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#3]
**Acceptance Criteria:**
- [ ] Criteria 1: Game transitions from main menu to options menu.
- [ ] Criteria 2: Menu has volume slider (not working yet)
- [ ] Criteria 3: Menu has player turn timer (not working yet)
- [ ] Criteria 4: Menu has language option (not working yet)
- [ ] Criteria 5: Menu has player name input (not working yet)

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
