### ISSUE TITLE
[USER STORY] As a user I want to be able to change the volume slider, so that the game volume changes

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#6]
**Acceptance Criteria:**
- [ ] Criteria 1: Volume slider show how high the volume is 1 - 100 %
- [ ] Criteria 2: % changes while moving volume bar
- [ ] Criteria 3: Volume changes when moved the slider and lets go of it

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
