### ISSUE TITLE
[USER STORY] As a user I want to be able to choose between turn timer option, So I can decide how much time a player has.

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#7]
**Acceptance Criteria:**
- [ ] Criteria 1: User can choose between 3 time buttons 30, 45 and 60 seconds
- [ ] Criteria 2: The chosen button is highlighted
- [ ] 
**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
