### ISSUE TITLE
[USER STORY] As a user i want to be able to choose between 2 languages so I can play the game in a language I understand

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#8]
**Acceptance Criteria:**
- [ ] Criteria 1: User can choose between English and Dutch
- [ ] Criteria 2: Game language changes once a language is chosen

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
