### ISSUE TITLE
[USER STORY] As a user I want to be able to change my name, so my name is correct

### ISSUE THREAD

**Issue by Thoredo** [Thoredo/battleship#9]
**Acceptance Criteria:**
- [ ] Criteria 1: Player can change their name in an input box

**Tasks:**
- [ ]

**Definition of Done:**
- [ ] All acceptance criteria are met.
- [ ] All tasks are done
